name: Deploy Spotify Actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build image
        run: docker build . -t sins621/test:latest

      - name: push image to docker hub
        run: |
          docker login -u sins621 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push sins621/test:latest

      - name: pull and run image on remote
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST }}
          username: sins
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script:
            cd spotify_actions
            docker run -p 8080:8080 -e SPOTIFY_ID=${{ secrets.SPOTIFY_ID }} -e SPOTIFY_SECRET=${{ secrets.SPOTIFY_SECRET }} sins621/test:latest
