name: Deploy Spotify Actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Build and Publish
        uses: actions/checkout@v4

      - name: Pull and Run Image on Remote
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST }}
          username: sins
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script:
            cd spotify_actions

            git pull origin master

            docker stop flask_app || true
            docker rm flask_app || true

            docker build -t flask_app_image .
            docker run -d --name flask_app \
              -p 8080:8080 \
              --env SPOTIFY_ID=${{ secrets.SPOTIFY_ID }} \
              --env SPOTIFY_SECRET=${{ secrets.SPOTIFY_SECRET }} \
              flask_app_image
