name: Deploy Spotify Actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 41.164.76.235 >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh sins@41.164.76.235 << 'EOF'
            cd spotify/actions

            git pull origin master

            docker stop flask_app || true
            docker rm flask_app || true

            docker build -t flask_app_image .

            # Run the container on port 8080
            docker run -d --name flask_app \
              -p 8080:8080 \
              --env SPOTIFY_ID=${{ secrets.SPOTIFY_ID }} \
              --env SPOTIFY_SECRET=${{ secrets.SPOTIFY_SECRET }} \
              flask_app_image
          EOF

